Add multiplex addon
Use case is codemirror breaks when using mutiple languages in one file

multiplexingMode is required by htmlembedded so needs multiplex addon.

Got this javascript error:

- "TypeError: undefined is not a function (near '...a.multiplexingMode...')"

This change fixes it.

See [1]

[1] https://github.com/codemirror/CodeMirror/blob/04d39f236a541104c3fccdfdf6ea164d6e4c74e7/mode/htmlembedded/htmlembedded.js#L18

Change-Id: I9c79d77c902dbb22271f33d9d6e2f9e50726d411